name: Build sample material

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: mdslides@0.3,mdbook@0.4,mdbook-mermaid@0.12
    
      - name: Build book-and-slides
        run: |
          ./training-slides/build.sh

      - name: Build example code
        run: |
          ./example-code/build.sh
  
      - name: Assemble Artifacts
        run: |
          mkdir -p ./rust-training
          mv ./training-slides/slides ./rust-training/training-slides-presentation
          mv ./training-slides/book ./rust-training/training-slides-book
          zip -r ./rust-training.zip ./rust-training

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: ${{success()}}
        with:
          name: Artifacts
          if-no-files-found: error
          path: |
            ./rust-training

      - name: Create and Upload Release
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./rust-training.zip
